[workspace]
resolver = "3"
members = ["eb_agb_psg_controller", "eb_agb_psg_macros", "eb_agb_psg_interop", "eb_agb_psg_format"]

[workspace.package]
version = "0.25.0"
edition = "2024"
authors = ["Emma Britton <emmabritton@pm.me>"]
license-file = "LICENSE"
repository = "https://github.com/emmabritton/agb_psg_controller"
readme = "README.md"

[workspace.dependencies]
agb_fixnum = "0.25.0"
serde = { version = "1", features = ["derive"] }
ron = "0.12"
quote = "1"
proc-macro2 = "1"
syn = { version = "2", default-features = false, features = ["parsing", "proc-macro", "printing"] }
