[package]
name = "eb_agb_psg_interop"
description = "Shared data model and song lowering for agb_psg_controller"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
repository.workspace = true
publish = true

[features]
default = []
std = []
quote = ["dep:quote", "dep:proc-macro2", "std"]
parse = ["dep:eb_agb_psg_format", "std"]

[dependencies]
agb_fixnum.workspace = true
eb_agb_psg_format = { version = "0.25.0", path = "../eb_agb_psg_format", optional = true }
quote = { workspace = true, optional = true }
proc-macro2 = { workspace = true, optional = true }

[dev-dependencies]
eb_agb_psg_format = { version = "0.25.0", path = "../eb_agb_psg_format" }
