name: Beta

on:
  push:
    tags:
      - beta_*
  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:

  check:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable

      - name: Install linux deps
        run: sudo apt-get update; sudo apt-get install --no-install-recommends pkg-config build-essential gcc-multilib libudev-dev libjack-jackd2-dev libjack-jackd2-0 libasound2-dev

      - name: fmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy -p eb_agb_psg_cli -p eb_agb_psg_interop -p eb_agb_psg_format -p eb_agb_psg_macros --features eb_agb_psg_interop/parse,eb_agb_psg_interop/quote --all-targets
      - name: test
        run: | 
          cargo test -p eb_agb_psg_interop --features parse,quote
          cargo test -p eb_agb_psg_format
          cargo test -p eb_agb_psg_macros

#  publish_gba:
#    if: startsWith(github.ref, 'refs/tags/beta')
#    name: Publish GBA
#    needs: [ check ]
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v6
#      - uses: dtolnay/rust-toolchain@stable
#        with:
#          components: clippy, rustfmt
#
#      - name: setup
#        run: |
#          cargo install agb-gbafix
#
#      - name: build
#        working-directory: eb_agb_psg_gba_tracker/game
#        run: cargo build --release
#
#      - name: build gba
#        run: agb-gbafix target/thumbv4t-none-eabi/release/game -o tracker_${{ github.ref_name }}.gba -tPSGTracker -cPSGT -mEB -r010
#
#      - uses: softprops/action-gh-release@v1
#        with:
#          files: tracker_${{ github.ref_name }}.gba
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_cli:
    if: startsWith(github.ref, 'refs/tags/beta')
    name: Publish CLI
    needs: [ check ]
    strategy:
      fail-fast: false
      matrix:
        target:
          - aarch64-apple-darwin
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: psg_cli_linux.tar.gz
          - target: aarch64-apple-darwin
            os: macOS-latest
            name: psg_cli_arm_mac.tar.gz
          - target: x86_64-pc-windows-msvc
            os: windows-latest
            name: psg_cli_windows.zip
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Install linux deps
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update; sudo apt-get install --no-install-recommends pkg-config build-essential gcc-multilib libudev-dev libjack-jackd2-dev libjack-jackd2-0 libasound2-dev alsa

      - name: build
        run: cargo build --release --target ${{ matrix.target }} --package eb_agb_psg_cli

      - name: Prepare build artifacts [Windows]
        if: matrix.os == 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          mv eb_agb_psg_cli.exe psg_cli.exe
          7z a ../../../${{ matrix.name }} psg_cli.exe
          cd -
      - name: Prepare build artifacts [-nix]
        if: matrix.os != 'windows-latest'
        run: |
          cd target/${{ matrix.target }}/release
          strip eb_agb_psg_cli
          mv eb_agb_psg_cli psg_cli
          tar czf ../../../${{ matrix.name }} psg_cli
          cd -
      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ matrix.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}